feat: Update project metadata and add TimeCraftModel class for time series forecasting

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,81 +1,93 @@
-name: Publish to PyPI
+# name: Publish to PyPI
 
-on:
-  push:
-    tags:
-      - "v*.*.*"  
+# on:
+#   push:
+#     tags:
+#       - "v*.*.*"  
 
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Validate version
-        uses: actions/checkout@v4
+# jobs:
+#   deploy:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Validate version
+#         uses: actions/checkout@v4
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.11"
+#       - name: Set up Python
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: "3.11"
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install build twine
+#       - name: Install dependencies
+#         id: install_dependencies
+#         run: |
+#           python -m pip install --upgrade pip
+#           pip install build twine
 
-      - name: Get version from tag
-        id: get_version
-        run: |
-          echo "VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV
-          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV
+#       - name: Get version from tag
+#         id: get_version
+#         run: |
+#           VERSION=$(git describe --tags --abbrev=0)  
+#           VERSION=${VERSION#v}
+#           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-      - name: Check if version is valid
-        run: |
-          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version format"
-            exit 1
-          fi
-          echo "Version format is valid"
+#       - name: Debug version extraction
+#         id: debug_version
+#         run: |
+#           if [ -z "$VERSION" ]; then
+#             echo "Failed to extract version"
+#             exit 1
+#           fi
+#           echo "Extracted version: $VERSION"
+#           if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+#             echo "Invalid version format"
+#             exit 1
+#           fi
+#         env:
+#           VERSION: ${{ env.VERSION }}
 
-      - name: Check if version is already published
-        run: |
-          if twine search $VERSION | grep -q "No matches found"; then
-            echo "Version not published"
-          else
-            echo "Version already published"
-            exit 1
-          fi
-          echo "Version not published"
+#       - name: Check if version is already published
+#         id: check_version
+#         run: |
+#           if twine search $VERSION | grep -q "No matches found"; then
+#             echo "Version not published"
+#           else
+#             echo "Version already published"
+#             exit 1
+#           fi
+#           echo "Version not published"
+#         env:
+#           VERSION: ${{ env.VERSION }}
 
-      - name: Package the project
-        run: | 
-          cd ./src
-          if [ -d "./dist" ]; then
-            rm -rf ./dist
-          fi
-          python -m build
-          if [ $? -ne 0 ]; then
-            echo "Build failed"
-            exit 1
-          fi
-          echo "Build succeeded"
+#       - name: Package the project
+#         run: | 
+#           cd ./src
+#           if [ -d "./dist" ]; then
+#             rm -rf ./dist
+#           fi
+#           python -m build
+#           if [ $? -ne 0 ]; then
+#             echo "Build failed"
+#             exit 1
+#           fi
+#           echo "Build succeeded"
 
-      - name: Check for version bump
-        run: |
-          git fetch --tags
-          latest_tag=$(git describe --tags --abbrev=0)
-          if [ "$latest_tag" != "v$VERSION" ]; then
-            echo "Version bump required"
-            exit 1
-          fi
-          echo "Version bump not required"
+#       - name: Check for version bump
+#         run: |
+#           git fetch --tags
+#           latest_tag=$(git describe --tags --abbrev=0)
+#           if [ "$latest_tag" != "v$VERSION" ]; then
+#             echo "Version bump required"
+#             exit 1
+#           fi
+#           echo "Version bump not required"
 
-      - name: Publish to PyPI
-        env:
-          TWINE_USERNAME: __token__
-          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
-        run: |
-          twine upload dist/*
-          if [ $? -ne 0 ]; then
-            echo "Upload failed"
-            exit 1
-          fi
+#       - name: Publish to PyPI
+#         env:
+#           TWINE_USERNAME: __token__
+#           TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
+#         run: |
+#           twine upload dist/*
+#           if [ $? -ne 0 ]; then
+#             echo "Upload failed"
+#             exit 1
+#           fi
